### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by loicparent** [Cap-go/capacitor-crisp#3]
Hello,

I encounter an issue with my IONIC application using CAPACITOR v3 when I try to build or run the app.
For example, when I use this command `ionic cap run ios --open`, the process stops with this error:

````
[capacitor] ✖ Updating iOS native dependencies with pod install - failed!
[capacitor] ✖ update ios - failed!
[capacitor] [error] Ignoring ffi-1.13.1 because its extensions are not built. Try: gem pristine ffi --version 1.13.1
[capacitor]         Analyzing dependencies
[capacitor]         Downloading dependencies
[capacitor]         Installing CapgoCapacitorCrisp (1.1.5)
[capacitor]         Installing Crisp (1.1.0)
[capacitor]         [!] The 'Pods-App' target has transitive dependencies that include statically linked binaries: (/…/app/test/test/ios/App/Pods/Crisp/Crisp.xcframework)
[capacitor]         
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor sync ios exited with exit code 1.
````

Could someone help me to identify what's wrong?

Also, I noticed that the documentation seems to be not up to date:
`import { CapacitorCrisp } from 'capacitor-crisp';` ⏩ `import { CapacitorCrisp } from '@capgo/capacitor-crisp';`

_Thanks for you help,
Loïc_

**Comment by loicparent** [comment]
Note: This issue in only for IOS. It works fine with desktop (web) version and with the Android version.

**Comment by riderx** [comment]
Thanks for the report @loicparent i did fix the doc issue, I will have look tomorrow for the build issue

**Comment by riderx** [comment]
@loicparent it seems you have a old version of crisp dependency. Can you go to the iOS/app forcer and do ‘pod update’

**Comment by loicparent** [comment]
Hello @riderx,

It works very well since the update of Podfile using `pod update`.

Thank you for your help!
_Loïc_
