### ISSUE TITLE
Question about the documentation and the tool

### ISSUE THREAD

**Issue by loicparent** [Cap-go/capacitor-crisp#4]
Hello @riderx,

I am doing some integration tests with this tool. 

**This is not an issue discussion but a list of questions:**

1. I wonder if I can add multiple segments at once using `setSegment()`. Same question for `setString()` and `setInt()`.
2. I wonder if I can add a private message or a private note using this tool.
3. I'm not sure I fully understand how I can register and set the token to manage multiple discussions within a single session. For example, I would like to use a different Chat on each page so that the Chat is relative to the page view.
4. Can I define the language of the Chat tool manually?
5. I noticed that the label of actions behind the "more actions" button stay in English even if the Chat is in French. is it something i can change?

Thank you for your help :)
_Loïc_

**Comment by riderx** [comment]
Hey @loicparent your questions are links to native crisp SDK this plugin is just a bridge to it.
I don't have the answer check the official doc or ask crisp team.
I think for the language someone already asked here :
https://github.com/Cap-go/capacitor-crisp/issues/1

I never used the plugin to have multiple session or segments, but i believe you can.

**Comment by loicparent** [comment]
Hello @riderx,

Thank you for your reply! I will make some tests :)

_Kind regards,_
_Loïc_

**Comment by loicparent** [comment]
Hey @riderx,

Just another question: Is it possible to manage the events to trigger a specific action of the user using this tool?

For example, I would like to show a custom notification when an operator reply to the message when the chat is closed/reduced.

I see that this is possible with the Web SDK but I would like to know if it was possible with this tool :)

_Loïc_

**Comment by riderx** [comment]
the native sdk is less complete than the web one, for the same reason as you i switched back to a  web implementation.
you can find mine here:
https://github.com/Cap-go/capgo/blob/main/src/services/crisp-web.ts

**Comment by loicparent** [comment]
Thank you for your quick reply and for the example!

The main issue with the Web version is that it does not fit very well the mobile interface.
(For example: the textarea stays in the bottom of the page and not above the keyboard such as the mobile SDK).

I will try with the mobile SDK first and look through the Web SDK maybe for later ;)

_Loïc_
