### ISSUE TITLE
The method "setInt" doesn't work on Android devices

### ISSUE THREAD

**Issue by loicparent** [Cap-go/capacitor-crisp#5]
Hello @riderx,

I noticed that the method `setInt()` works fine with IOS devices and with desktop browsers but, it seems to be an issue with the Android devices. When I call this function as in my exemple below, the data is not sent to the Crisp website.

```` js
CapacitorCrisp.setInt({
  key: 'test',
  value: 123
});
````

I don't know if this is related to this plugin or if it's related to the native Crisp SDK but I informe you here :)

_Kind regards,
Loïc_

**Comment by riderx** [comment]
Thanks for the feedback @loicparent, something a bit odd in the native SDK is the chat have to be open in native to allow any data to be sent.
Did you had the chat open before sending ?

**Comment by loicparent** [comment]
In fact, I call multiple functions one by one in a main function like this example:

````js
CapacitorCrisp.setUser(); // ✅
CapacitorCrisp.openMessenger(); // ✅
CapacitorCrisp.setSegment(); // ✅
CapacitorCrisp.setString(); // ✅
CapacitorCrisp.setInt(); // ❌
CapacitorCrisp.setString(); // ✅
````

So the chat should be opened but I don't wait till the promise finishes before calling the other functions.

**Comment by riderx** [comment]
Thanks for the details, i did check the swift code, and it's exactly the same structure for `setString` and `setInt` see below
<img width="496" alt="CleanShot 2022-10-03 at 22 56 28@2x" src="https://user-images.githubusercontent.com/4084527/193680973-2fd93223-690d-47e9-bcaa-1a3550618e85.png">
<img width="503" alt="CleanShot 2022-10-03 at 22 56 36@2x" src="https://user-images.githubusercontent.com/4084527/193680962-f04780dc-9e41-4ed0-9a20-7578319b401f.png">
Value is get with `getInt` as it's the type we see in they doc here https://docs.crisp.chat/guides/chatbox-sdks/ios-sdk/
So i believe the SDK has issue or they doc is wrong.
Can you report that to they github : https://github.com/crisp-im/crisp-sdk-ios/issues
and link this issue in the issue you create, them i will see it, and be able to answer if needed

**Comment by loicparent** [comment]
Hello @riderx,

Note: This is not an issue of IOS but an issue with Android.

After looking through the code, I thing I found what is wrong :)

In the Android SDK, the type of the expected value for the function `setInt()` is `String` instead of `int`. 
You can see it in the file `CapacitorCrispPlugin.java`:

![demo](https://user-images.githubusercontent.com/11327909/193765101-1e6bfc7f-ca08-425f-9ae2-7a42b9ee370c.png)

_Kind regards,
Loïc_

**Comment by loicparent** [comment]
I just tried modifying the code a bit and it works :)

Here are the changes I made:

![demo-2](https://user-images.githubusercontent.com/11327909/193769047-c3096a89-d950-4253-87d6-1d6c60c94187.png)

**Comment by riderx** [comment]
oh good cath, you want do to a PR?

**Comment by riderx** [comment]
Sorry for checking the wrong platform ! thanks for the fix, new version will be publish by CI

**Comment by riderx** [comment]
`1.1.7` is available https://www.npmjs.com/package/@capgo/capacitor-crisp
do `npm i @capgo/capacitor-crisp@latest` and `npx cap sync` to try it :)

**Comment by loicparent** [comment]
> oh good catch, you want to do to a PR ?

Sorry for my late reply. I see that you've changed the code. Thank you :)
